name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install python3-venv
        run: |
          sudo apt update
          sudo apt install -y python3-venv

      - name: Set up venv and install dependencies
        run: |
          python3 -m venv venv
          ./venv/bin/python -m ensurepip --upgrade
          ./venv/bin/python -m pip install --upgrade pip
          ./venv/bin/python -m pip install -r requirements.txt

      - name: Run Tests
        run: |
          ./venv/bin/python -m pytest

